feat(logging): Log HTTP request / response headers
gravitee-io/gravitee-policy-logging pull request #1
Opened 2017-03-06 10:04 UTC by brasseld

Closes gravitee-io/issues#481

2017-03-28 20:39 UTC, NicolasGeraud requested changes

2017-03-28 20:39 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/logging/LoggingPolicy.java
> +                request.headers().forEach((headerName, headerValues) -> LOGGER.info("<<< {}/{}: {}: {}",
use response not request

2017-03-28 20:39 UTC, NicolasGeraud commented on src/main/java/io/gravitee/policy/logging/LoggingPolicy.java
> +                request.headers().forEach((headerName, headerValues) -> LOGGER.info(">>> {}/{}: {}: {}",
Headers are only logged if you POST something. On a GET we have nothing

2017-09-20 20:14 UTC, brasseld commented
IMHO, this issue is not more accurate with the logging feature.

WDYT ?

2018-05-02 07:45 UTC, closed without merging